name: Update Problemsets Daily
on: 
  schedule:
    - cron: '00 00 * * *'
jobs:
  Update-Problemsets:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job runs everyday at 00:00 UTC"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
             python -m pip install --upgrade pip
             pip install bs4 html5lib
      - name: Updating problemsets with update.py
        run: |
             python3 ${{ github.workspace }}/update.py
      - name: auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updating problemsets daily
      - run: echo "This job's status is ${{ job.status }}."
